debug_mode: true
lowercase_data: true
pad_token: <pad>
bos_token: <bos>
eos_token: <eos>
unk_token: <unk>
propn_token: <propn>
max_sequence_length: 100
max_vocab_src: 50000
min_freq_src: 2
max_vocab_tgt: 50000
min_freq_tgt: 1

emb_dropout: 0.3
batch_size: 5000
encoder_emb_size: 500
encoder_hidden_size: 500
encoder_layers: 1
encoder_dropout_rate: 0.1
decoder_emb_size: 500
decoder_hidden_size: 1000
decoder_layers: 1
decoder_dropout_rate: 0.1
out_dropout: 0.2
coverage_dropout: 0.2

maximum_decoding_length: 100
bahdanau_attention: true
coverage_phi_n: 2
coverage_required: false
coverage_lambda: 0.01

n_epochs: 20
init_optim: adagrad
init_learning_rate: 0.01
init_epochs: 1
optim: sgd
learning_rate: 1.0
learning_momentum: 0.9
grad_clip: true
max_grad_norm: 1.0
val_slices: 5
lr_decay_patience_steps: 10
lr_decay_factor: 0.9
lr_decay_threshold: 1.5
lr_decay_min: 0.005
